### ISSUE TITLE
*self.image_size in model.py

### ISSUE THREAD

**Issue by aditipanda** [ChengBinJin/V-GAN-tensorflow#12]
**self.X = tf.placeholder(tf.float32, shape=[None, *self.image_size, 3], name='image')**

This line gives:
SyntaxError: invalid syntax

I'm using TensorFlow 1.7.0 in python 2.7, Ubuntu 16.04.
Did you mean self.image_size*self.image_size ?

**Comment by aditipanda** [comment]
This worked after I used shape=[None, self.image_size[0], self.image_size[1], 3], as self.image_size = (400,400).

**Comment by ChengBinJin** [comment]
@appyfizzA Cool!
