### ISSUE TITLE
打扰！！

### ISSUE THREAD

**Issue by wangziyan1234** [ChengBinJin/V-GAN-tensorflow#19]
您好  程序有个小问题请教下您   ，下面是model.py里定义的函数，每次我训练的时候，程序都会中断，测试了下问题出在这个函数，但又不知道具体是什么问题，请问您有什么好的建议吗
def sample_imgs(self, x_data):
       return self.sess.run(self.g_samples, feed_dict={self.X: x_data})

**Comment by ChengBinJin** [comment]
@wangziyan1234 
可以告诉我 Error message 是什么吗？ 这个是training过程每隔一段时间做sampling查看现在的效果怎么样。因为GAN刚看Loss信息是不能确定训练现在做的好不好。
