### ISSUE TITLE
I changed the dataset, but the result of validation was very poor.

### ISSUE THREAD

**Issue by little1TouwaErio** [ChengBinJin/V-GAN-tensorflow#20]
Hello, I used your code on the segmentation of the two-dimensional lung fissure. The input image is a slice of the three-dimensional lung. I want to output the image of the lung fissure. When I verify it, the output image is always black. I am using the first discriminator. Excuse me, what is the problem with the verification of the generated image? (I have tried a lot of values for the threshold of zero processing, the generated image is still black), I hope you can help me. I am looking forward to your reply. 

![7%@26CSKKLTC5Q1IUWEFM60](https://user-images.githubusercontent.com/51114312/68658425-5e03ba00-0570-11ea-8f91-2b931dfe2c62.png)
@

**Comment by ChengBinJin** [comment]
@little1TouwaErio 
I see. Can you explain what is the meaning of the second image and the third image? Is the third one a gold standard image?

**Comment by little1TouwaErio** [comment]
The second&nbsp; one is sampled by the network during training，and&nbsp;the third one is a gold standard image.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Cheng-Bin Jin"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月22日(星期五) 晚上7:28
收件人:&nbsp;"ChengBinJin/V-GAN-tensorflow"<V-GAN-tensorflow@noreply.github.com&gt;;
抄送:&nbsp;"416580793"<416580793@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [ChengBinJin/V-GAN-tensorflow] I changed the dataset, but the result of validation was very poor. (#20)




@little1TouwaErio
 I see. Can you explain what is the meaning of the second image and the third image? Is the third one a gold standard image?

**Comment by ChengBinJin** [comment]
@little1TouwaErio 
I think you selected the wrong discriminator. The first discriminator is the pixel-wise discriminator. It distinguishes the generated image from the real one based on a pixel level. Can you try the fourth one, image-level discriminator? Because the lung fissure just can be recognized by watching the whole area of the input image.
