### ISSUE TITLE
关于patch-GAN的疑问

### ISSUE THREAD

**Issue by Xuecheng-anhui** [ChengBinJin/V-GAN-tensorflow#21]
与传统的相比，区别是不是图片经过判别网络的输出是一个二维的tensor？而不是一个实数。

**Comment by ChengBinJin** [comment]
@Xuecheng-anhui 
是的，patch-GAN的 idea 来自Isola的 pix2pix 论文里。那里提到这种patch-GAN是更关注receptive field小的区域，所以对细节的关注度比较高。
