### ISSUE TITLE
'none' type object issue

### ISSUE THREAD

**Issue by nswathi10** [ChengBinJin/V-GAN-tensorflow#24]
When I run the main.py as instructed i get the following error:-
**TypeError: object of type 'NoneType' has no len()**
I traced back the error and found out which line is causing the error and it is:
**def get_img_path(target_dir, dataset):-
    img_files, vessel_files, mask_files = None, None, None**
Its the get_img_path function written in utils.py
the complete error is posted below:-
**Traceback (most recent call last):
  File "/content/V-GAN-tensorflow/codes/main.py", line 45, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/content/V-GAN-tensorflow/codes/main.py", line 37, in main
    solver = Solver(FLAGS)
  File "/content/V-GAN-tensorflow/codes/solver.py", line 29, in __init__
    self.dataset = Dataset(self.flags.dataset, self.flags)
  File "/content/V-GAN-tensorflow/codes/dataset.py", line 27, in __init__
    self._read_data()  # read training, validation, and test data)
  File "/content/V-GAN-tensorflow/codes/dataset.py", line 46, in _read_data
    self.num_train = int(len(self.train_img_files))
TypeError: object of type 'NoneType' has no len()**

Somebody please help. i am approaching my project deadline and this is a major part of my work. i am stuck. please help

**Comment by saberlilyzz** [comment]
hi，Have you solved this problem? I encountered the same type of error。

**Comment by nswathi10** [comment]
no i was not able to solve it ..although the author told me to specify
the path of the dataset properly. i checked and it is the correct datapath
which i have given. still same error occurs.

**Comment by nswathi10** [comment]
Hey it was the silliest mistake that I had done. Just letting you know if
it helps you. you have to run the main.py as:-

python main.py --train_interval=1 --ratio_gan2seg=10 --gpu_index=0
--discriminator=image --batch_size=1 --dataset=STARE --is_test=False

I had given --discriminator=[image].am new to python and do not know
how to pass arguments. However this solved my issue and the code is
running perfectly.

For more info:- check your dataset path in dataset.py code, if it is
properly defined. My dataset path was:-

self.train_dir =
"*/content/V-GAN-tensorflow/data*/{}/training/".format(self.dataset)
self.test_dir = "*/content/V-GAN-tensorflow/data*/{}/test/".format(self.dataset)
Would be glad if it helped.
